import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'cover', // docs/intro.md
      label: "Cover Page", // what shows in the sidebar
    },
    {
        type: 'category',
        label: 'Philosophies',
        link: {
          type: 'generated-index',
          title: 'Philosophies',
          description: 'A collection of methodologies and the reasonings behind following them.',
          slug: '/philosophies',
          keywords: ['philosophy', 'philosophies']
        },
        items: [
          'philosophies/philosophy-of-philosophy'
        ]
    },
    {
        type: 'category',
        label: 'Politics',
        link: {
          type: 'generated-index',
          title: 'Politics',
          description: 'Oddly\'s Political opinions and philosophies',
          slug: '/politics',
          keywords: ['politics', 'policies']
        },
        items: [
          'politics/immigration'
        ]
    },
    {
      type: 'category',
      label: 'Software Design Documents',
      link: {
        type: 'generated-index',
        title: 'Software Design Documents',
        description: 'Software Design Documents for Oddly\'s hobby projects.',
        slug: '/software',
        keywords: ['software', 'software-design']
      },
      items: [
        'software/gnomicon-knowledge-base'
      ],
    },
  ],
};

export default sidebars;
